version: '3.7'
services:
  postgres:
    container_name: postgres
    image: "postgres:latest"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=MYPASS

  kafka:
    container_name: kafka
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: '''
      conveyor-finish-registration:1:1,
      conveyor-create-documents:1:1,
      conveyor-send-documents:1:1,
      conveyor-send-ses:1:1,
      conveyor-credit-issued:1:1,
      conveyor-application-denied:1:1
      '''


  zookeeper:
    container_name: zookeeper
    image: wurstmeister/zookeeper
    expose:
      - 2181

  grafana:
    container_name: grafana
    build: './grafana'
    ports:
      - 3000:3000
    user: root
    volumes:
      - ./grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - DATASOURCE_URL=http://prometheus:9090


  prometheus:
    container_name: prometheus
    image: prom/prometheus
    user: root
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/config/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/container:/prometheus

  gateway:
    container_name: gateway
    build: ./gateway
    ports:
      - "8080:8080"
    depends_on:
      - application
      - deal
    links:
      - application:application
      - deal:deal
    environment:
      - APPLICATION_CLIENT_URL=application:8080/api
      - DEAL_CLIENT_URL=deal:8080/api

  application:
    container_name: application
    build: ./application
    depends_on:
      - deal
    links:
      - deal:deal
    ports:
      - "8081:8080"
    environment:
      - DEAL_CLIENT_URL=deal:8080/api

  deal:
    container_name: deal
    build: ./deal
    ports:
      - "8082:8080"
    depends_on:
      - kafka
      - conveyor
      - postgres
    links:
      - conveyor:conveyor
    environment:
      - KAFKA_SERVER=kafka:9092
      - CONVEYOR_CLIENT_URL=conveyor:8080/api
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=MYPASS
      - SPRING_JPA_HIBERNATE_DDL-AUTO=create

  conveyor:
    container_name: conveyor
    build: ./conveyor
    ports:
      - "8083:8080"

  dossier:
    container_name: dossier
    build: ./dossier
    ports:
      - "8084:8080"
    depends_on:
      - kafka
      - deal
    links:
      - deal:deal
    environment:
      - DEAL_CLIENT_URL=deal:8080/api
      - KAFKA_SERVER=kafka:9092
      - KAFKA_GROUP_ID=dossier.group.id
