version: '3.7'
services:
  postgres:
    container_name: postgres
    image: "postgres:latest"
    networks:
      network-service:
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=MYPASS

  kafka:
    container_name: kafka
    image: wurstmeister/kafka
    networks:
      network-service:
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: '''
      conveyor-finish-registration:1:1,
      conveyor-create-documents:1:1,
      conveyor-send-documents:1:1,
      conveyor-send-ses:1:1,
      conveyor-credit-issued:1:1,
      conveyor-application-denied:1:1
      '''


  zookeeper:
    container_name: zookeeper
    image: wurstmeister/zookeeper
    networks:
      network-service:
    expose:
      - 2181


  conveyor:
    container_name: conveyor
    build: conveyor/
    networks:
      network-service:
    ports:
      - "8081:8080"


  deal:
    container_name: deal
    build: deal/
    networks:
      network-service:
    depends_on:
      - postgres
      - conveyor
      - kafka
    ports:
      - "8083:8080"
    environment:
      - CONVEYOR_SERVICE_URL=http://conveyor:8080/api/conveyor
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=MYPASS

  dossier:
    container_name: dossier
    build: dossier/
    depends_on:
      - kafka
    networks:
      network-service:
    ports:
      - "8084:8080"

networks:
  network-service: