build-deal:
  image: maven:3-jdk-11
  stage: build
  script: "mvn  package -f deal/pom.xml -DskipTests"

deal-conveyor:
  image: maven:3-jdk-11
  stage: tests
  services:
    - postgres
    - nartemev/conveyor/conveyor:latest
  variables:
    POSTGRES_DB: postgres
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: MYPASS
    KAFKA_SERVER: kafka:9092
    CONVEYOR_CLIENT_URL: conveyor:8080/api
    SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
    SPRING_DATASOURCE_USERNAME: postgres
    SPRING_DATASOURCE_PASSWORD: MYPASS
    SPRING_JPA_HIBERNATE_DDL-AUTO: create
  script: "mvn test -f deal/pom.xml"