build-deal:
  image: maven:3-jdk-11
  stage: build
  script: "mvn  package -f deal/pom.xml -DskipTests"

test-deal:
  image: maven:3-jdk-11
  stage: tests
  services:
    - postgres
  variables:
    POSTGRES_DB: postgres
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: MYPASS
    CONVEYOR_CLIENT_URL: localhost:8080/api
    SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/postgres
    SPRING_DATASOURCE_USERNAME: postgres
    SPRING_DATASOURCE_PASSWORD: MYPASS
    SPRING_JPA_HIBERNATE_DDL-AUTO: create
  script:
    - "mvn package -DskipTests -f conveyor/pom.xml"
    - "java -jar conveyor/target/conveyor.jar"
    - "mvn test -f deal/pom.xml"